version: "3.8"
name: logsview

services:
  proxy:
    build:
      context: ./docker-images/proxy
      dockerfile: Dockerfile.Debug
    volumes:
      - ./docker-images/proxy/server.Debug.conf:/etc/nginx/conf.d/default.conf:rw
      
  web:    
    build: 
      dockerfile: ./docker-images/web/Dockerfile.Debug
    volumes:
      - ./web:/logs:rw
    container_name: logs_web
    restart: unless-stopped
    expose:
      - 5173
    networks:
      - logs

  
  server:
    build: 
      context: ./server
      dockerfile: ../docker-images/server/Dockerfile.Debug
    volumes:
      - ./server:/server:rw