
version: "3.8"
name: logsview

services:
  
  proxy:
    build:
      context: ./docker-images/proxy
      dockerfile: Dockerfile.Debug
    expose:
      - 80
    networks:
      - logs

  web:
    build: 
      dockerfile: ./docker-images/logs/Dockerfile.Debug
    working_dir: /logs
    expose:
      - 5173
    volumes:
      - ./web:/logs:rw
    networks:
      - logs
  
  server:
    build: 
      context: ./server
      dockerfile: ../docker-images/server/Dockerfile.Debug
    volumes:
      - ./server:/server:rw
    expose:
      - 80
      - 2331
    networks:
      - logs


  db:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: someone
      POSTGRES_PASSWORD: baboobaySomethingLoool
    volumes:
      - storage:/var/lib/postgresql/data
    networks:
      - logs
    expose:
      - 5432

volumes:
  storage: {}

networks:
  logs:
    driver: bridge
    ipam:
      driver: default