FROM nginx:1.25.4-alpine3.18-slim

RUN apk add gettext

COPY ./server.Debug.conf /etc/nginx/conf.d/default.conf.template

EXPOSE 80

CMD /bin/sh -c "envsubst '\$ROUTE' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'