/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLogsByRangeModel
 */
export interface GetLogsByRangeModel {
    /**
     * 
     * @type {number}
     * @memberof GetLogsByRangeModel
     */
    end: number;
    /**
     * 
     * @type {number}
     * @memberof GetLogsByRangeModel
     */
    start: number;
}

/**
 * Check if a given object implements the GetLogsByRangeModel interface.
 */
export function instanceOfGetLogsByRangeModel(value: object): boolean {
    if (!('end' in value)) return false;
    if (!('start' in value)) return false;
    return true;
}

export function GetLogsByRangeModelFromJSON(json: any): GetLogsByRangeModel {
    return GetLogsByRangeModelFromJSONTyped(json, false);
}

export function GetLogsByRangeModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLogsByRangeModel {
    if (json == null) {
        return json;
    }
    return {
        
        'end': json['end'],
        'start': json['start'],
    };
}

export function GetLogsByRangeModelToJSON(value?: GetLogsByRangeModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'end': value['end'],
        'start': value['start'],
    };
}

