/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Loglevel } from './Loglevel';
import {
    LoglevelFromJSON,
    LoglevelFromJSONTyped,
    LoglevelToJSON,
} from './Loglevel';

/**
 * 
 * @export
 * @interface LogDto
 */
export interface LogDto {
    /**
     * 
     * @type {any}
     * @memberof LogDto
     */
    additionalData?: any;
    /**
     * 
     * @type {string}
     * @memberof LogDto
     */
    controllerName?: string;
    /**
     * 
     * @type {Loglevel}
     * @memberof LogDto
     */
    level: Loglevel;
    /**
     * 
     * @type {any}
     * @memberof LogDto
     */
    message?: any;
    /**
     * 
     * @type {string}
     * @memberof LogDto
     */
    requestId?: string;
    /**
     * 
     * @type {string}
     * @memberof LogDto
     */
    serviceName?: string;
    /**
     * 
     * @type {string}
     * @memberof LogDto
     */
    title: string;
}

/**
 * Check if a given object implements the LogDto interface.
 */
export function instanceOfLogDto(value: object): boolean {
    if (!('level' in value)) return false;
    if (!('title' in value)) return false;
    return true;
}

export function LogDtoFromJSON(json: any): LogDto {
    return LogDtoFromJSONTyped(json, false);
}

export function LogDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogDto {
    if (json == null) {
        return json;
    }
    return {
        
        'additionalData': json['additional_data'] == null ? undefined : json['additional_data'],
        'controllerName': json['controller_name'] == null ? undefined : json['controller_name'],
        'level': LoglevelFromJSON(json['level']),
        'message': json['message'] == null ? undefined : json['message'],
        'requestId': json['request_id'] == null ? undefined : json['request_id'],
        'serviceName': json['service_name'] == null ? undefined : json['service_name'],
        'title': json['title'],
    };
}

export function LogDtoToJSON(value?: LogDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'additional_data': value['additionalData'],
        'controller_name': value['controllerName'],
        'level': LoglevelToJSON(value['level']),
        'message': value['message'],
        'request_id': value['requestId'],
        'service_name': value['serviceName'],
        'title': value['title'],
    };
}

