/* tslint:disable */
/* eslint-disable */
/**
 * server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum Loglevel {
    Debug = 'debug',
    Info = 'info',
    Warning = 'warning',
    Error = 'error',
    Critical = 'critical'
}


export function LoglevelFromJSON(json: any): Loglevel {
    return LoglevelFromJSONTyped(json, false);
}

export function LoglevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Loglevel {
    return json as Loglevel;
}

export function LoglevelToJSON(value?: Loglevel | null): any {
    return value as any;
}

