FROM rust:1.75 as build

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends --assume-yes \
      protobuf-compiler

RUN cargo install cargo-watch
RUN cargo install diesel_cli
RUN cargo install cargo-expand
RUN rustup component add clippy
RUN rustup component add rustfmt
WORKDIR /server
ENTRYPOINT cargo-watch -x run
# ENTRYPOINT cargo run || tail -f /dev/null
